---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: workverse-synapse
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData: {}
  template:
    metadata:
      name: workverse-synapse
      namespace: {{ .Release.Namespace }}
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
