apiVersion: v1
kind: Service
metadata:
  name: work-flow-service
spec:
  selector:
    app: work-flow
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007
  type: NodePort
