---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: relay-secret
  namespace: workverse
spec:
  encryptedData:
    API_URL: AgA6PmAp+53ls2ps407diKZdVpuKqMWNL2kC2MY/vLTMgsh2bpXi7PXyahA9LDjIjNrDw0v8zIJBS24psDmF1Qf4mnvs0N/sc0IxZ/P038EQ10bMZa6oQ8fGVMweyfcl/NTPNgAJUvW6PjimP8+o9hEMba0Ap+po8n3v1vmLkIHB3MSqv8/YO1yqIy7gX1XM0JJBJlR7SfVKfbKMPDDDN7WYywL1YSMg+/YHqv14U781LssLodS6L6g6OK+8v8MelCDLcjMkKHTqtlKYiyrUZfTt5u3S/7aJjgobOsljcocg98HCNq5ctBDzeyGtTNqxFAouQ+2B8QLAtvisUI8ZPicAj/vQwSEtpLoRfb59+VnKsImeYU0LcEzRdr6vsM4KKlt0iYipaORRuaPP86L+sQ9rxjl9olvfMuyohLrpihhthA7MbxyMfclnZ5YynFxHnrcdAO7RjkbLhXDXHx3C15MPizyETy1LJUooZhG/+rLL+39ihL3q5WcMXX6ajwJYJNDQ7nH5+vWygjxDMNCjP2eQD/4rdyZ8Fg9zIHWJp2albw/RO/8UTpc7e22MfIAAA74W6pxuOvFs9WL7LZHfmNW1SJOlOjS42VosAIhmzZ729WgE8AlX6BPrV93u4ALafMN0NhTk1mAB8ZtWD/JIpn9QfISDtUBz/GQj3YJ6KvMqd5HMAzOw3SFhFzSBQ/p3x4QVpXkLFqTEALulQVE+4zN42el6yvQTvmbwPysCcpYeEI+g5SrPQfzuhtA=
    REDIS_URL: AgCxRgy4ceaDZx9q9OgBKR6zmidokGobtEqUES/tQXSw3Gv/WR4ZA6g2MoaC+eOR7zJoa6fN8rxkW66swMMNz+pguDb+SyqkULZnNb1h+taF7vDflRzcMAQ7x0J0OYTMQm0IlqMJoSWp6VfLk97XC9piP+bMC9kgReUMhExfNtO2kSa5pTpyPvqgnGsftf9z02TRvWN73eXSu8uVKb9lV7t0wgHiN6ivJzNLTFiE35d4FuC6MXHmqTPXjviu+/apogmgtPkS7hCxlxDtbGTvpzQ+o30zRinOV/x/mMnij6rJMqV4+UjoQtGDjbXvwaXdk11D2R0Mgwz/PhityWdCSldVGAt0eKvJ3JF5cdcvnIcau81lJPKRFXlIsaIoZzaDhscx2vmZNhhQ8mX8EYs4b+pursZfMBKDJK8qGJQutDlA4238r4mdBCNnGq0eBpVyfyB9heF/0XLhqjKEc+S4mkG6HnRy4D4341wk9/Kya5uKVo9Gx2AZnyIFvxZdcca0FaFc28w9A7L6gSgDL4qtIuXueHW/1k8m8oDPa5OY3RGUefIUoemwOAbvztltFSgQASP7xmnpnCWkYeSjNZN0VyqgTf1ggKWKOd0RCO0W2UqQgmVhZ7iHQICuD3xYbcP7ykVpfsJjJ3HZG2HuCzXKL9efdTPCJl1hkbtZG5MEPVGhFZMEWGSHXAjoy39Nt67ScFX1nsRfaI9ZL+V8K4S5h48rKbIwQ4riDj8YcTTxEDd6reXzCdfONLIYu5LwHUM/b2rotmaVQJmBWtTGaRbqJWh7uifAIXiZA5lNhJwJ5seslTQWiRXGrpF4ykqm3y0o41Uc8RmpFhSdAKCl0E414AXn+hydGw==
  template:
    metadata:
      name: relay-secret
      namespace: workverse
    type: Opaque
