replicaCount: 2
image:
  repository: aravmenon12/workverse-orion
  pullPolicy: IfNotPresent
  tag: "30aa3a4496c7b387cc43ecd4701c4bae8a60ddbd"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels:
  app: orion-workverse
  tier: orion-api
podSecurityContext: {}
securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
service:
  type: ClusterIP
  port: 3002
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: orion-workverse.arav.space
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: orion-workverse-tls
      hosts:
        - orion-workverse.arav.space
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
livenessProbe:
  tcpSocket:
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  tcpSocket:
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
envFrom:
  - secretRef:
      name: orion-secret
