replicaCount: 2
image:
  repository: "aravmenon12/workverse-stream"
  tag: "73f0fa4dce419e85a7b7220057cd0c9989880631"
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels:
  app: workverse-stream
  tier: stream
podSecurityContext: {}
securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
service:
  type: ClusterIP
  port: 3010
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: stream-workverse.arav.space
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: stream-workverse-tls
      hosts:
        - stream-workverse.arav.space
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
envFrom:
  - secretRef:
      name: workverse-stream
