---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ws-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    DATABASE_URL: AgCDvgCQUEXIoemgc1lq2Fud4aPWjG3v84psS4ysPRU/HFG+tJ0zQKlpVwk/SAM48jWymrLxyV0xJQ1D6yLEAKdXFIVEiz6b9jh8XWFiew4elnZF/lqjJ8Zqqs2kzU+/0geDjH6Oeo2rMMFAShtq9OlUN4YLqdUvixGLSOhlRK2bP8XyMFeXLqX/8qqTLrD8GNBX42n9VpLlGTtV+AM0wOxL7YBjCQawXlVbpealtPsL1EeeDvfugP3qB07OIAQ96tL2wUsech4Go0qgJ6PWGp9SvUpemEE5md76l7SR/eRpCTWqtiZuT4JjnZyCT5Ax5gW592OmhI1LTwD/lpSd4eEUlF+HArLdL+7SsLumlpJHcuQ6LgecbopetaYhHGRtNmqsZGuZxZ/rL+Lr3qD0BoX5BLBv1D5gAK9+rNS7uMm378yVeXyOKDy/2q2TPuGZoBGljd/xJkb7eJm3UZ3rNERtAlaVe2N+jhxCDQNCHA+sGPWSXCACBsteTLc+Wy1HVg1CBLR9mG4PoTW64E2D944IT3P7ILN2JnRyArMU05e5OTtO61gFf0TDS7+ZZM6Hdeh3T9SiKjP5EbKJC5doOiSdAOOwvU7BgAuyg/A/FNluflmeiB2sx+wi4Ejm+qnrxsA2EkuZU9o1FkxUH1UzAOZHr6vnxP0hOszr2R0yIQJkZPZwOo9q0GcPW7PfC0jiUQmDPE5/Hn/CB9cQHAU0TBls8e4ppglKmeuSGoVrnaDxXS3q+KF4YYbq8HhJGGstI4H9V29KVFduL6yMvA5bZqK6P0xvRfiXAN5nU5cY7Y9yyomNqPzVrQ04yAP2PmBCFqQaEW7bctwy98m25XS5ga708B8N+M0NG+QszvU0Rw3Ra93Q6KA5uw1SSdihiZRrehjOZzmRmqfOxw==
    JWT_SECRET: AgCO0TEQrWFyFaadFC8cUYEoLWKZPNFCMZhpSvfBSnNGFX2BDzFNfE3lAchEb2AEPu4XcK7tDfVGBIZsM3g6tmVjxN95kACzXAoO4leAmOWKw/r6Iw8d3RuwyK1O5SeqDFTaYdo4lZw3RWn4AZTa4v5P+3bKNZoj21+H51+hmDrXYH8LSESkIGTa684JffzCCnI8KYKxnKFk/Q/DAN0E5bhxNMfXi0Lpv8zOB2Rs4ajmNQMoEIPW2bzwASLVENcMgDQBQwj6nfduoEH09clyp13ZHajHRP1DAd1Hlyk2y8KeyxZQ8e2uiCjAxgIwANtJ7HJzbgEzsGf6H1RDc9uBfqT2Mss5v9++5zgXPYB7Krfu9pzW9GsH6QpAWeYy5DtxVMK+ultzJKRUtgjpbqo8VtUpG1Hc/XvflTJHYAuqP63wZyto0CROoYlGzOel216TxQ+balMEN9ukK4+iKiS8JFWt3zacBklcg2j+s2rVAE4v10eYtMmzso93UXsO6wW0WfJ5PAiS8lmsPG6+6oF/BOLwpg+RZhp4gvrZpxK0Ylpr2cVvgQtz0clFx1PBGB6mrmzmaLNL1eQcKXlNWdHV4sJWhpISQO5PaUxpXIwEcKv0U0rePRb6xgecrJyMn2p1fVfCpuU4JYR8BYzDevLR4W770Rp9ZeOhtWmwbkQ5D46IhmACWYxxmqtC7FJtwgY7iAJ0AYV5iwe29uiGsGXN7LEsWFVWiPTlg1NGX+jkrPQ9lJ49BiW2nWvyfJa4tTM=
  template:
    metadata:
      creationTimestamp: null
      name: ws-secret
      namespace: {{ .Release.Namespace }}
