replicaCount: 1
image:
  repository: aravmenon12/trial-ws
  pullPolicy: IfNotPresent
  tag: "8c728e7736c215e165246c62de6239b73bca8afd"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels:
  app: websocket
  tier: ws-api
podSecurityContext: {}
securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
service:
  type: ClusterIP
  port: 3002
ingress:
  enabled: false
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ws-api.arav.space
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ws-api-trial-tls
      hosts:
        - ws-api-trial.arav.space
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

envFrom:
  - secretRef:
      name: ws-secret
