apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trial-services
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: backend
          - name: frontend
          - name: websocket
  template:
    metadata:
      name: "trial-{{ .name }}"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/arav-menon/staging-ops.git
        targetRevision: HEAD
        path: "prod/trial/{{ .name }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: workverse
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
