apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workverse-namespace
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/arav-menon/staging-ops.git
    targetRevision: HEAD
    path: prod/workverse
    directory:
      recurse: false
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: workverse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
