---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workverse-forger
  namespace: workverse
spec:
  encryptedData:
    REDIS_URL: AgC6REsQJbdCBawkANeTJ1u/xnu3dXY0K52Re67GS4Hs6LrzGchjbytmHjV5gebmmBLBTT7F9BqGI/SyIUc/buUMarXdunPqvEqvCBwp7lf5LpbJ3JmaC0U8E7ww3OGjDJytIJ6ujgNon1zbrWH1LeatMITgNr/NrFnUx+NxyZi2qiLOFWKWX9d4H8pfsdcDkYnT1j1DuaWI3BCGQS139tPqKsw757Sv9L+Am9xXFatHFIR9dzzSpDUv8trSiyQx+mJunLwM6WtsG64w5dQ7JrbzffyXUQMN2PvSJPveU7M6eiGVOBDmZ+yuYEW11g5/Lq4/dBrqTlt4K630Ds75Ta/Oxg6t0FAZsRKMSV8xc7648AUqQby2rW2ZckJMQtGrd/4AG9LQfCV9E0RcBPw8IjworqtQK24t5cjafd38k1ZpD/qUKsy+62l0Z52TpajNan0Yr8oZrvXhihvltXgiBPAyAgBgMrPeV/tDOT57fSPc3CAdtPNjGKPe1XOHS87V8oA+yQbDTAXbkNSnm1b7nQTp16uvdkP6Twhp70Sg3UL49ReosN/2TL7oroP17CSH2CwYkkhuUvnQvR87m6okQBmK6kRRUbgbyLFUWyuZrOX6cUlGJYo3l2KqoJgmXuA49CaNmBujc046qOgRh0X/odMPQ1cItj6xTxPE0GOsksWHtpus/Q8MKwDjgTL03AIzOSU8mZI45HkPfJoLHbnWNgIaRm+ZidK19+1ay25rtkxL4EzRcCkpd7oNuDOpobz6PbxGC0zO1iNyTZylVainRbCESsOGgTqa5c1GBZRHZr9Ds3fUPe551iqADmqObVvHX/YQTSO1yxboLccyKQ30f/snL7AofQ==
  template:
    metadata:
      creationTimestamp: null
      name: workverse-forger
      namespace: workverse
    type: Opaque
