apiVersion: v1
kind: Secret
metadata:
  name: workverse-secret

stringData: DATABASE_URL="postgres://postgres:workVerse_code@localhost:5432/postgres" N8N_ENCRYPTION_KEY="b37dda183b16f501242f62c506d1c6b187140209187771d4825a7fe3f943abe9"
