---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    DATABASE_URL: AgBre8TZOCEqJbFH27WDq8F1+z9LHCsywYEZavPOLFr5VV2oKXIeV15MUrxQxMEP1aB/QqHYGWw80Yk9pdTu95uEAll6oE6wdW6P63Sj644X79lYrKyIUhBGt8W2EZ476BcAQNkAX9NZzdLHPt6Uy+dMERUH7Ko3Hw5yqzZ8VmDamstQtoCQGGSqIbxDYPrydiU61Ab7nlmb7We8bFumx+hDVRCD3ii9S9+eiMZayeUAGqWSi4IHLn5DsvgdWkG0B+8vCTwcq/yKlYxg9QJMVoJL5ZTG1qI4fk6kkRqP01EwEbRLaTSmGKODXXFUKLMPmHfxBiXxGIHFg6EsjfsreW5I0OxusJ4FTEcfaxVRbhI5BtpmmzQHb/GBxfLR2AVmgwiib+WSYMkErmMJ7VlVgcMEt++mmZ7tdvRfJFCOe5l9mWj8SAeaVXT3dH5yQf6g/DP/LtOHtdxplj3BX6Uov2s09wcgy//FfI/4I2Kfu2NOKvA1TtFT7HcZ7cUm7fPv9OhpNAWXoYqwWgEZ7me2h4YcqEOILAepEywy6iN9+rSVZ0IeB5BCp6GbF4w4wJwWBM8RRNYtR7mAIJcQmmrQt+emu/wctObcLqbxMcS7cyF5tDOoE5WTs+nkPj4jZ8E0M3jayU4O3WKFgc/tgvoFUUIYbhk+A2HJ6WnYRznEPE15EKariU6GX+TM0qdJf3x+N+tEJMyf+oqCE7ZWDGPlHqx7RZ36tcIuiZvynOaOlCeWnEdQuoAaxub0erdxIAA+MT0goAwYhskZUuzdNt6wATD9OgKI5b9h+AWP07/d3cycwvDPyZB9RHI3tpeLVia0cCtjG9iNT3RcUBfqUuJtY3BvS14EEOgL7LpwfhfZ85GRenlMiN+bUItc6EiXG8FiOW6hPJ8pceqhYQ==
    JWT_SECRET: AgCFpcSrAY3BCVx02OkbymZn1zdumFMmx89FNsF5ByZAUde/8EuQMpLEDGuUh9vR8A6WluZr77/GgZSWR4wy//rxZLpMBXoUmRhYHlG2zKwt6xS+DsG02Mv5PK0hU0X23GS86wnTTUA7/jzWMtbpxgGuE9O2rH6RKosPxBrScCCzKLgelCkIZgpDU7jZHRLQHl0GE1qjLVrlN672GT9vi9GhuPOS3JvKWfictw70re5qvl8cVspiN0P+pZ46YpM8Ipw9ZukpE2W3+YDRC9j+7kHo7EOgGSuhKnLkqtU0ToT8GwB/+jACFbuHNjtA7AHL4f+8CYmO0CUNjqhqj+YlRqFjYkRG75kC1FrdTzUmj3vcNX5Wkc4pmt/bXRw4LBNXbcCco2iMDjOmaCjpr3YNPfnVxTFaJtmRP3dTsKMBLzS8wD1/l/U11gcjq5KNoK4TKvHmZ1yS9NPFLWv3Kibnd/Bv/lSjMt7HhZk96ojTRnRiXjZjvUbXPHJGTvRo8MQOXN+jAGw7xwhiC3IpeACi7XQkyfTdcNFpVnSvzVfRapkQo0qkugAmHCf2wJcJfmbnxB2G+7SImGLW2CoMgoDfyzAEkVdOg+j5ZpVnZCY4bfPFE68gpiMiuB240IdqBidplEv8qzR3tt6qzeqMAa0IGA/0Vkocrxx+m6XK0HnkhJUDxOkLMTw/XuQz+r5Y1hTIsHyxn/iDGtP82D83j0eTl7izdkPHBoN3rJxZvQv9zfth5i++nEOdHiTyD7jAJnU=
  template:
    metadata:
      creationTimestamp: null
      name: backend-secret
      namespace: {{ .Release.Namespace }}
