---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workverse-mail-forger
  namespace: workverse
spec:
  encryptedData:
    RESEND_API_KEY: AgAPM+W6m2lU6tpqb+7GgX3RP5usew6rPgogmtWAbFDEhfMDwW/EVUu2VSpEhoDWMdC7G2vZ4Kht6jYNq23XZKpxK0oAKElwarDoAUJXUKIMdYkfsoP/9H0Bou5v8AamUE22PzUggnx236LzyfFmKsOz+AUgaJeGOV6Y579U0+x1WoET+eAr3GHLw2l0wYCUuiQpj+mEn4KYduUL0rX+0KTapHBMSH1cJihNiT5tLs7H113R28sLb6cq4QziBD9caVFZpoT+YIE3OA44fdC1m5NW2Z+S8gWrSO2OU2BhcohAsmQcYnjGqT6NEQ7qurdwhboP4qDVgqGygAR5Zj0xu/IrYK/2UJZF+MEWxQgNDHGdNPbat0PxPBZF3PqMSPeTkt3Za3Ab20s6X/fSgpzq8zxMRyruzdSReHFlKELjtKy1612ewdrxFMJa/DE3s6JOJWOi5e1a0xPV+Yf9I6Kth6Rpz8B21+rREILeAlGAohVNqtgwJLF7WH09ckG1SC2oQItk+HMZ0hqTmhFlX7knV4ZV9P7lB/a3Rnr5CRzCuKTeCV4KdjZxurfwwzAeDdUdflVXOii8EuV2szGdJkAHz9YxSv9PvQx3/enLwRk6HYYGNvsXWjJDBximJ9P2Hb/QpBs2ydF7Yf3Ni8aGzcr/klAdndsUE42aFxZNGUITe6QsTEC++WfYdNv6YQDwHI5vffE/SAuGBdpe+VL3KBe1PM9BV8UXu4Ohn4HIzwLyezPqAOADU3o=
    RESEND_FROM_EMAIL: AgAo4r3JdaFUs+B4g+Q72ZewA/5t8dLe+TQSZmFqK0dbW/tvhfQjDWcGdoIorIfz32qN/dQ9jOPdXoBdKeFzHEvte6nZUipKwzAcn9WAPVEy2hYOR95QY6TEHBsOqGHCJJTVnlw9BMGsY6ZTykyR9oQ0zfdNO6IzDbAcQULf5cKDDzldeDQM06Rz383idkhVmxiH3H/I6JvMTEMLYf6RWoe+Tq+n3yCpnvwFYCkFW3L+mkWzXsEqv394pFVh9CAHTu+Q6pheWIDPczNU0hJy3WaYwAvVDEhE32d1vD2XKWICc4e++L4hv8A7tsQU98idEeWrg62D+FBkLymW6wWM9MwMS99ZDcywTS9C7oULWYJyBoXae281NV+WeHn9iSVG7Quus1qj7h/8ygHvxgsagqoHGEtkUA//Pp7EAI2Mezq7tM99WCz1FjrAvAjs4FqYIxPID5L4CxwI+GUJSbMTI7ojhYTkCEa3HjXhq+qso9YxjOQJ9VGSMjUCqrQty9ka9xT2V9a22kkTMzoL7+IGQ71mZGvyzEw3mWdciuCfqrYlnzl1n7pIP9ar1Mm+X7KNiDihM9rqpDAk8KSwBalB9QubZ6OlXM5upRlzSiy7f5QCnktcarMCd19FpnppoVhzEiEG89VsaL+TDPELPlX/xQaCDi0PSRLUghFQrH2fYjDUILiTpkAzcmwK/owr/cwSHJWXkR7vuTmSxLtd2nM3282EmxLLBnuEcK6XfAupWrRjtHVNFrF8m7nDNFas0rSn
  template:
    metadata:
      creationTimestamp: null
      name: workverse-mail-forger
      namespace: workverse
