---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flux-secret
  namespace: workverse
spec:
  encryptedData:
    REDIS_URL: AgBH8D+NEdBkKrRFI2OzRU+RzEKXFw1EMQ9ZOyGb4/vv815HlmRTk7cO1udZhO8y/iapXxIfmOCh4B6dxTTpHJxogEdA4vgsVB0znUeh0qIDN1xkb8U5vySXHpgjs/EQRx0AouY97VDNvORV0DfwSZeTPpFGTOLA+nuHsBrJzRrFcrv+a6HvN0bOdC71vxJtPTbsyUjezdvNoOm15DgQpgMTH/0yKCQ0eq4PukA26bnJlTDu2t5PofNiJbI2zXFyvDB3NmRHFDHK/VNOxK1FLCc+JCZwE/A2IuU4pLeqTfHPwRPl6kGdSsJ7wCySUkADvttaoFM3FgdlAal78rRqyKs2v7TM6IX4V99p8e/VskSr3B+XELXm+Lcw5p9nx2vVcJ2s0IrE85d1LVXXyf9v0UWBC1a/rr/0MoDH7i+f4rpYW/7TEAfFfmcJSNQ3NXXKb7zuBBfDXFa1avp4zSX26cS9C3nghaEsJ2viPAE7B8ZgLIgwFi/HjadHLUBx/VZhfLoks4XAQuPIvo+LwYgZnQ+2w0xVbqCybQyVCBD9NGuEHklhEdb+lCU/fdoYpbX/SfNWmnr38RgGBKGniwC+gp0YXBKHEUnWH1wADJi5XHfWQXzAic7yYoFJu6NuFIZXLXxa17hDsoKLy4ckzVQDAePTujoTsZJWqw8C75J2qWRTSfnNlRdCJyamgsxHorVVaHboCHHy9hOsZOWlPHkEzxaGDkWp6mZJfJKWELmdvYAz4gx5cpNpa2nxiaKDxaeVeSRvX5gVvCdvdQ3UDkgzw1l/9+K+0/iH4uRkvKiDU2pMR7rjLbrYRRR/EUPaqeWSvyn8f/I2CuKzhCqBkecqWW0e/A9M6g==
  template:
    metadata:
      creationTimestamp: null
      name: flux-secret
      namespace: workverse
    type: Opaque
