---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flux-secret
  namespace: workverse
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    REDIS_URL: AgBDLBjvl9bN+vWG8Z/DwhEusBKpAO6GjI4wDHBJqmMkRb9SQWxMhqdXo05Z3Bfe34T0/De9XJiJ2K4DxW0U5S8nTVXyuL2hi4EPYxlGzDs2MzKXVNtaoa8sXLb7dJ+f0eddR6t0OwAgGEpU2H6JU23DU/m8hTcNo/FPoexwvgxmYdF2wMQcf4Qnu9wtp98DlFLOXRspeiQwSxVjIS/fe4aYHzxL50SvTC8ixzbprcyfAlZfxPmEWjv0KpWqvvQNUYMe7t9PzkhCDGOs3UDcZEzoZRrqkOfFZhH55zzG27/rVZ7q6f8IFwFw61ZfMlbnQjwPqpAg5IEqkoqv38Fy5D7cssyAm+4+oDfInM5rPpLHRehmd4xn5F1MOy450dCprQmkerUqXUYPbztXUWRZEL+avPBpkyB75mOLN4Nqpcu5tQqvUvEBt7/KIyTUlrw0T31vWMX0S5JZEUCkAeBFfWVp0gKjpVbV2YzQOdAvqt6Hof/Y6mT0IUNe0F0rDU3QF5lwy6aHXf+tfjhEg1yl9RKB76c8liBbwwdYYyg5lk7Kzabm827gLV/QFt2Akl4klyKrs4aG+uiiypUBtxvaxT4lvKywDQtEUDxCKGsZ55oTqFezUJZCthVmZmt2bMv8rO78EFeZDg60sNowV0D9HrP3a0cCFFOMDwUENn3mzLWIN8Okr3illuUd2STjKsdpA/m6qN6m6hqalHivFv+yFg9xV/KcZJqSbpNkiBMIAlUFpON0G1VxEAl6ouDbvTWofusQohcE8c5DemdE9c4xEXG7FeeIoTQ5E49YkfFudOexZykqjoAaiXWK8EPA277xaTVmT/f7VztdsoFtNIYjtn2qvflGMw==
  template:
    metadata:
      name: flux-secret
      namespace: workverse
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
    type: Opaque
