---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flux-secret
  namespace: workverse
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    CORTEX_API_URL: AgCnBgM28k2uA/dfMfTTzP50vKn3gt3nKUkE7u3+ePxtbGFGfmNXchTMTSYvg1DVk0ho97un7tF7N9/ah9cXnz25j3S/N47dhvyoYMX0GZYEEHvwE1gDkh4dSngYZ3AX+ekUPBWWbpvv+PGzC/856xhUyGeWys4jVYqpKYkLy6eZkjYYel7OSRR7JdHRFqJMXceunEMMHHyjgN2Y83qsnzT2hTtsejR7h/XUHAPFSZQ3crqcRFmciWskv7xH08VKV0kpLNEcm8cmnWhuruggUNYnEfEdFEV0gCSP6WkZeFSC69wWQTmZZn3gnDoVdIoc0mRjezd4ugek0cLNu6Qt0rRhHlMeBGj2ZSTsHjtfQyWL+PZhlomTfI2maUL2Y0vVW5JCaWgZOIIo10i773ud3+ltfFZI+FNvSdMpcE9ApRGZmBjfY1g8n1cjLX6qyISjVuG1DSIN9iwqaVD74G2981ERaktAbxClkwGwBFxkt/GzVFrluojNaaGVqbMCvtBmU4oHTLc3M5ikPo6OnA/zrLzZIxyIfII4cBR2WnMYQ1DT4OWXMx9nWsFISj0abD0dwLGJ1kyF26yrc0urcc0idIJM4wJ3/WrNlzlk1W8FkUI9AWPQFDntpHj426S38usN35yYYOEpxa0I5dNbZx7g2KAIAPpi50hyvi7wV0JyAdZEOeY3Ruy+8PFI4hc/D4xPD2GOI0LqkoP56FgbPBQfB68BeD9iON65Ql5bt4bIVuHh7YBRYhLdYw0gmoJRJ3+vUiGQQytAsfZsRg==
    REDIS_URL: AgADQTgKeJqYsPTtAxcqbEVQ207Vkjo9nllJMKD27yI3DwDTCDDv6bvDJr6VeF836zH9qdS6ZvVCg/68SG/b5Sods2ygcfzwjnYoBbVChTeK9Zmx5mCWMIn1C+bWAvsuxJ/ONljvpXBTMlGnIjB6tgv5A7xoq+M83szVcjeLYrDYE+mra7hj/JlBDA8GNiuqIDxI3wVbsQ60i6sfa7NQyGq8npmdFAiePL9jXTNNCIYMPW8Ejk0nEiXC/ehSIla7E2u4v0/DsNPJgPUM4uzEhwjQb1FkGlMe/dzegpx6exXCI15+2wVVRi9kmSO8WaajzFvXER7jziXQADK9KdRQf1lZV0kwXjL1ftOcwaBw64R5p1wfQASsgKr8rNl60RWy2kSiCfM92aGSrYW/V72iVxpnQCZKlKjyb8H9sinZrW60zMVAia9h5ZN/NOOZL/FjLXS6KlI6hD5v60tNDHYoQiL3d01HTXjqlGqpC6ewBmy0EzWs1Qmvxh8CnoXHGl2kIpUW6m2clzqHnqtUtjrx0HIUUXW6qtLlIBJIp8Tujrs9JtcrzJP+dkmiWiLRPCCyve9Y2P8WK2vrasLSAysr5YY+m1jqCrq0jmsjRygkZiUCspz0XPgND2V+CcBZ2aMobSdWiq9OUyDLBvFbCFdCVerPfFMdZbwD4Q5Y2Au6bO3FC/ASgQCPskr5nSWL2lipVuBqeP16Hgp7xWh228SKCpLeTNkoNLxYw4fRrZenmchWzscXm3xERgILRDIGoyxqGj7jZMgfA7VT1AB/tobVlVO6VBitwG3gaCyznb1QfVACMefONgVNnfqST8MmB0LZg/5grM7BCyVgsRxbLnnGv/hxZXn/Cg==
  template:
    metadata:
      name: flux-secret
      namespace: workverse
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
    type: Opaque
